### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by mekodak** [nioc/synology-srm-php-api#1]
you are saying
`To install with composer:

composer require nioc/synology-srm-php-api
Or download [latest release](https://github.com/nioc/synology-srm-php-api/releases/latest) zip archive,`

but latest release is still asking for autoloader.

where do i find autoloader to use on my Syno NAS ?

**Comment by nioc** [comment]
You're right. I forgot to add vendor dependencies in release archive (because in my own use case main, php app install vendor dependencies with composer).
I'll add a full release.

**Comment by nioc** [comment]
So there are now 2 archives:
- `synology-srm-php-api-1.0.0-without-vendor.zip`, the original one without vendor dependencies (needs to use composer install),
- `synology-srm-php-api-1.0.0.zip`, version with vendor dependencies (autoload and logger).

You should use the second one, I close the issue, let me know.
