### ISSUE TITLE
Look in Safe Access

### ISSUE THREAD

**Issue by mekodak** [nioc/synology-srm-php-api#2]
Look in 'Safe Access for online "users" / profiles, so i am able to se is a profile is online an the maby use it for some smart home system.

**Comment by nioc** [comment]
Sound like a good idea 👍🏻
Could you find what is the API method and parameters?

**Comment by nioc** [comment]
I found this one in the GUI:
``` ini
?additional=["device","reward","total_timespent","has_avatar"]&api=SYNO.SafeAccess.AccessControl.ConfigGroup&method=get&version=1
```

Results looks like:
``` json
{
  "data": {
    "config_groups": [
      {
        "config_group_id": 2,
        "device_count": 2,
        "devices": [
          "11:22:00:00:00:01",
          "11:22:00:00:00:02"
        ],
        "has_avatar": true,
        "last_update_avatar": 1587490775,
        "name": "Bob",
        "pause": false,
        "profile_id": 2,
        "rewards": {
          "ultra_rewards": []
        },
        "timespent": {
          "has_quota": false,
          "quota": 0,
          "total_spent": {
            "normal": 312,
            "reward": 0
          }
        }
      },
      {
        "config_group_id": 3,
        "device_count": 2,
        "devices": [
          "11:22:00:00:00:03",
          "11:22:00:00:00:04"
        ],
        "has_avatar": false,
        "last_update_avatar": 0,
        "name": "$lan$",
        "pause": false,
        "profile_id": 3,
        "rewards": {
          "ultra_rewards": []
        },
        "timespent": {
          "has_quota": false,
          "quota": 0,
          "total_spent": {
            "normal": 439,
            "reward": 0
          }
        }
      }
    ]
  },
  "success": true
}
```

So, API request should be to `SYNO.SafeAccess.AccessControl.ConfigGroup` and params:
- method: `get`
- version: `1`
- additional: `json_encode(['device', 'total_timespent'])`

To set online status, it will require `is_online` attribute from `SYNO.Core.Network.NSM.Device` with params:
info: `basic`
method: `get`
version: `4`

I think a new method `getProfiles` which will returns profiles list with following information:
- config group id
- profile id,
- name,
- avatar url (if `has_avatar` is true `/webapi/_______________________________________________________entry.cgi?api=SYNO.SafeAccess.AccessControl.ConfigGroup.Avatar&method=get&version=1&config_group_id=<config_group_id>&v=<last_update_avatar>&SynoToken=<token>`),
- online status (true if at least one device is online),
- devices count,
- online devices count,
- (optional) devices list:
  - mac,
  - online status,
  - name.

Does it sounds good to your needs?

**Comment by nioc** [comment]
I worked on this feature last night, it won't return avatar url (which require a token, not session id).
Release tonight 😉

**Comment by mekodak** [comment]
Can you make an example that on request of 'name' return state of online trye or false ?
Like: http://domain.com/example.php?name=Bob
Return: TRUE

Or like: http://domain.com/example.php?mac=11:22:00:00:00:04
Return: FALSE

**Comment by nioc** [comment]
Hello, what you ask is not the purpose of a wrapper, it is the end user code.

You can filter the list returned on the name attribute:
```php
$name = "Bob";

$accessControlGroups = $client->getAccessControlGroups(true);

foreach ( $accessControlGroups as $group ) {
  if ( $name === $group->name ) {
    return $group->online;
  }
  return false;
} 

```

**Comment by mekodak** [comment]
How to get rhe RAW JSON instead of all that login confirmation and DEBUG data?

**Comment by nioc** [comment]
It is the output of the function. 

See https://github.com/nioc/synology-srm-php-api/blob/master/example.php#L53

```php
$accessControlGroups = $client->getAccessControlGroups(true);
$logger->info(json_encode($accessControlGroups));
```

**Comment by mekodak** [comment]
> It is the output of the function.
> 
> See https://github.com/nioc/synology-srm-php-api/blob/master/example.php#L53
> 
> ```
> $accessControlGroups = $client->getAccessControlGroups(true);
> $logger->info(json_encode($accessControlGroups));
> ```

That i got, but how about all befor 'INFO - Get devices successful'

**Comment by mekodak** [comment]
> > It is the output of the function.
> > See https://github.com/nioc/synology-srm-php-api/blob/master/example.php#L53
> > ```
> > $accessControlGroups = $client->getAccessControlGroups(true);
> > $logger->info(json_encode($accessControlGroups));
> > ```
> 
> That i got, but how about all befor 'INFO - Get devices successful'

I did just edit the analoge format!
