### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by stephan1827** [nioc/synology-srm-php-api#3]
Hi,
this is not really an issue but maybe you can point me in the right direction. I am trying to enable or disable a WIFI network. I am reading the settings with this funtion

`	/**
   * Retrieve Wifi network settings
   *
   * @return {Promise<Boolean>} Network settings
   */
	async getWifiNetworkSettings () {
		const data = {
			method: 'get',
			version: 1,
			api: 'SYNO.Wifi.Network.Setting',
		};
		return (await this.request('/webapi/entry.cgi', data));
	}`

and this works fine. But I cant figure out how to change the settings. I created this function

`	/**
   * Set Wifi network settings
   *
   * @param {object} data Updated policy rules
   */
	async setWifiNetworkSettings (settings) {
		const data = {
			api: 'SYNO.Wifi.Network.Setting',
			method: 'set',
			version: 1,
            params: {
                profiles: settings
            }
		};
		return await this.request('/webapi/entry.cgi', data);
	}`

but it will allways come back with error 114. I tried all kinds of variations but it just wont take the new settings even if I try to write the data I received with the get function. I checked the web code and they do pretty much the same thing in nsm-WIFI in the function appendSetWebapis. 

Is there something I am missing here?

**Comment by nioc** [comment]
Hello, you are close 😉
You can have a look to my NodeJS wrapper in which I added a `switchWifiRadio` method for switching on/off a particular radio:
https://github.com/nioc/synology-srm-nodejs-api/blob/master/lib/index.js#L493-L531

**Comment by nioc** [comment]
May be, you just missed the `profiles` serialization with `json_encode`.

**Comment by stephan1827** [comment]
You are the man, I thought I tried that variant, but I guess I didn't. :-)

Thx again
